---
- name: node_base | Apply nftables config
  ansible.builtin.systemd_service:
    name: nftables
    state: reloaded
  listen: apply nft

- name: node_base | Start nftables service
  ansible.builtin.systemd_service:
    name: nftables
    state: started
    enabled: true
  listen: apply nft
